print("="*60)
print("NEED MORE CLEAN CAR IMAGES")
print("="*60)
print(f"\nCurrent: 230 clean images")
print(f"Target: ~1700 clean images")
print(f"Need: ~1470 more images")
print("\n📥 Download from these sources:")
print("\n1. Google Images:")
print("   - Search: 'new car showroom'")
print("   - Search: 'clean car exterior'")
print("   - Search: 'pristine car'")
print("   - Search: 'car dealership inventory'")
print("\n2. Kaggle datasets:")
print("   - https://www.kaggle.com/datasets/jessicali9530/stanford-cars-dataset")
print("\n3. Save all images to:")
print("   ~/Desktop/valet/dataset/undamaged/")
print("="*60)
